### ISSUE TITLE
new pattern: functional PersistentStateMachine

### ISSUE THREAD

**Issue by eoln** [mojaloop/sdk-scheme-adapter#245]
**Problems spotted in existing code**:

- duplicated implementations, for example, [_save](https://github.com/mojaloop/sdk-scheme-adapter/blob/master/src/lib/model/OutboundTransfersModel.js#L708) & [load](https://github.com/mojaloop/sdk-scheme-adapter/blob/master/src/lib/model/OutboundTransfersModel.js#L726)
   - versus functional way: 
      - https://github.com/mojaloop/sdk-scheme-adapter/blob/master/src/lib/model/common/PersistentStateMachine.js#L14  
      - https://github.com/mojaloop/sdk-scheme-adapter/blob/master/src/lib/model/PartiesModel.js#L57

- pattern where we have duplicated code in Outbound and Inbound service to generate PUB/SUB channel name: 
   - https://github.com/mojaloop/sdk-scheme-adapter/blob/master/src/lib/model/OutboundRequestToPayModel.js#L269
   - https://github.com/mojaloop/sdk-scheme-adapter/blob/master/src/InboundServer/handlers.js#L467
   - also in tests
   - versus functional common way:
       - https://github.com/mojaloop/sdk-scheme-adapter/blob/master/src/lib/model/PartiesModel.js#L175
       - https://github.com/mojaloop/sdk-scheme-adapter/blob/master/src/lib/model/OutboundTransfersModel.js#L178 

- need to rebind class methods
   - https://github.com/mojaloop/sdk-scheme-adapter/blob/master/src/lib/model/OutboundTransfersModel.js#L82-L83
   - versus functional way:
      - https://github.com/mojaloop/sdk-scheme-adapter/blob/master/src/lib/model/PartiesModel.js#L30

repo links:
  - PersistenStateMachine: https://github.com/mojaloop/sdk-scheme-adapter/blob/master/src/lib/model/common/PersistentStateMachine.js

  - example of usage: https://github.com/mojaloop/sdk-scheme-adapter/blob/master/src/lib/model/PartiesModel.js

**Question**: Should we use this new pattern, if yes what is our decision about existing models?
**Proposed solutions**: 

1. leave as it is and allow two patterns to be used
2. don't allow new pattern and refactor PartiesModel and related using the existing one
3. allow new pattern and mark old code as technical debt
4. allow new pattern, don't allow technical debt, so refactor old code

**Comment by lewisdaly** [comment]
Thanks @eoln  - I think you got your answer from slack? Is there any other input needed before going ahead with a solution?

**Comment by eoln** [comment]
@lewisdaly there is a need to make a decision: which proposed solution is widely accepted.

**Comment by lewisdaly** [comment]
Cool. #4 is my preference, but it might be nice to get an estimate of the effort required before you get too stuck in refactor-land.

**Comment by eoln** [comment]
after a short talk during today's daily PISP team decided to go on #3, grab some more knowledge about the application of the new pattern, deliver some generic solutions for common models and then decide how to refactor the legacy code.

**Comment by mdebarros** [comment]
> Cool. #4 is my preference, but it might be nice to get an estimate of the effort required before you get too stuck in refactor-land.

I support this too.

**Comment by mdebarros** [comment]
> after a short talk during today's daily PISP team decided to go on `3. allow new pattern and mark old code as technical debt`, grab some more knowledge about the application of the new pattern, deliver some generic solutions for common models and then decide how to refactor the legacy code.

I think we should still go with 4. The only difference that I see from 3 to 4: that there is be a story created on 4 for the refactoring of old code, this story can be prioritised by the PISP team, even picked up by another stream or perhaps an individual from the community.
