### ISSUE TITLE
TypeError: Cannot read property 'toLowerCase' of undefined at setConfig

### ISSUE THREAD

**Issue by bogere** [mojaloop/sdk-scheme-adapter#91]
There is problem with reading the values from the configuration file.
because everywhere there is `toLowercase()` method ,  the server complains of undefined value.
It is happening  both in the plain source code for sdk scheme adapter server and also the docker container for  scheme sdk adapter.

**Error stacktrace**
`(node:3177) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'toLowerCase' of undefined
    at setConfig (/Users/bogeregoldsoft/work/kanzu_money/mojaloop_Docs/sdk-scheme-adapter/src/config.js:113:75)
    at /Users/bogeregoldsoft/work/kanzu_money/mojaloop_Docs/sdk-scheme-adapter/src/index.js:89:15
    at Object.<anonymous> (/Users/bogeregoldsoft/work/kanzu_money/mojaloop_Docs/sdk-scheme-adapter/src/index.js:106:7)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
(node:3177) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)`

**Docker container**
`bogeregoldsoft@Goldsoft-OK src % docker-compose up
src_redis_1 is up-to-date
Starting src_scheme-adapter_1 ... done
Recreating src_backend_1      ... done
Attaching to src_redis_1, src_scheme-adapter_1, src_backend_1
scheme-adapter_1  | (node:1) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'toLowerCase' of undefined
scheme-adapter_1  |     at setConfig (/src/config.js:113:75)
scheme-adapter_1  |     at /src/index.js:74:15
scheme-adapter_1  |     at Object.<anonymous> (/src/index.js:91:7)`

**Comment by elnyry-sam-k** [comment]
Closing as outdated (no movement for more than 4 years now)
