### ISSUE TITLE
Max clients are being reached to Redis

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/sdk-scheme-adapter#97]
**Summary**:

During load testing on the SDK-Scheme-Adapter the following error response occurs after 10k requests on the Outbound API for Transfer requests:

Example request
```
curl -X POST \
  http://perf1-simulatorXX.YYY.ZZZ:3501/transfers \
  -H 'Accept: */*' \
  -H 'Accept-Encoding: gzip, deflate' \
  -H 'Cache-Control: no-cache' \
  -H 'Connection: keep-alive' \
  -H 'Content-Length: 397' \
  -H 'Content-Type: application/json' \
  -H 'Host: perf1-simulatorXX.YYY.ZZZ:3501' \
  -H 'User-Agent: PostmanRuntime/7.20.1' \
  -H 'cache-control: no-cache' \
  -d '{
    "from": {
        "displayName": "tarken",
        "idType": "MSISDN",
        "idValue": "12213803913"
    },
    "to": {
        "idType": "MSISDN",
        "idValue": "11113803912"
    },
    "amountType": "SEND",
    "currency": "USD",
    "amount": "1",
    "transactionType": "TRANSFER",
    "initiatorType": "CONSUMER",
    "note": "test payment",
    "homeTransactionId": "123ABC"
}
'
```

Response:
```JSON
{
    "message": "Ready check failed: ERR max number of clients reached",
    "transferState": {},
    "statusCode": 500
}
```

The following log entry can be found on the scheme adapter:

```log
scheme-adapter    | {
scheme-adapter    |   app: 'mojaloop-sdk-outboundCache',
scheme-adapter    |   err: {
scheme-adapter    |     message: 'Ready check failed: ERR max number of clients reached',
scheme-adapter    |     stack: 'ReplyError: Ready check failed: ERR max number of clients reached\n' +
scheme-adapter    |       '    at parseError (/src/node_modules/redis-parser/lib/parser.js:193:12)\n' +
scheme-adapter    |       '    at parseType (/src/node_modules/redis-parser/lib/parser.js:303:14)',
scheme-adapter    |     command: 'INFO',
scheme-adapter    |     code: 'ERR'
scheme-adapter    |   },
scheme-adapter    |   msg: 'Error from REDIS client getting subscriber',
scheme-adapter    |   timestamp: '2019-11-27T11:48:58.126Z'
scheme-adapter    | }
```

**Severity**:
High

**Priority**:
Critical

**Expected Behavior**

The transfer should be sent through to the Mojaloop Switch.

**Steps to Reproduce**
  1. Send 10k+ Transfers to the Outbound API (no parties or quotes tested)
  2. Jmeter config used:
    - Threads: 1
    - Delay: 3ms
    - Requests: 25k
    - Ramp-up: 10s

**Specifications**
  - Component (if known): SDK-Schema-Adapter
  - Version: 8.5.7
  - Platform: n/a
  - Subsystem: n/a
  - Type of testing: Perfromance Testing
  - Bug found/raised by: @mdebarros 

**Notes**:

1. Redis by default has a setting of 10k max connections
2. Redis Client connections are being created whenever the Outbound andTransfersModel and AccountsModel are instantiated as per the following lines of code:
https://github.com/mojaloop/sdk-scheme-adapter/blob/master/src/lib/model/AccountsModel.js#L107
https://github.com/mojaloop/sdk-scheme-adapter/blob/master/src/lib/model/OutboundTransfersModel.js#L125

- Severity when opened: High
- Priority when opened: Critical

**Comment by bushjames** [comment]
resolved
